### ISSUE TITLE
I am a newbie. Can I skip the webgl1 and learn the webgl2 course directly?

### ISSUE THREAD

**Issue by WREQI** [sketchpunk/FunWithWebGL2#13]
I am a newbie.
 I didn't find the complete webgl1 course online.
Can I skip the webgl1 and learn the webgl2 course directly?

**Comment by sketchpunk** [comment]
Yes. WebGL 1 things are done COMPLETELY different plus there is features in WebGL 2.0 like VBOs that is important to speed up and simplify your rendering system. So webgl1 is only needed if you need to do something that is backwards compatible with old hardware.

Here's a lil secret... WebGL gets translated into Direct X on Windows and Metal on Macs, So even though its the same OpenGL API, it gets run on other graphics apis.

Last note, any OpenGL 3+ tutorial is easily transferable to WebGL 2, the APIs are the same. WebGL 2.0 is actually modeled after Open GL 3.0 ES, which is the graphic api you'd use if you where to do this from scratch on android devices. So you don't have to just look up webgl 2 info, OpenGL 3 would do and there is more info in that realm.

Good Luck!

**Comment by WREQI** [comment]
Thank you
